/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clips': typeof ClipsRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clips' | '/events' | '/live' | '/settings' | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clips' | '/events' | '/live' | '/settings' | '/setup'
  id: '__root__' | '/' | '/clips' | '/events' | '/live' | '/settings' | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipsRoute: typeof ClipsRoute
  EventsRoute: typeof EventsRoute
  LiveRoute: typeof LiveRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipsRoute: ClipsRoute,
  EventsRoute: EventsRoute,
  LiveRoute: LiveRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
